/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author purba
 */
public class GetOrder extends javax.swing.JFrame {

    /**
     * Creates new form GetOrder
     */
    PreparedStatement pst = null;
    ResultSet rs = null;
    String dbName = "gmsDB";
    String user = "root";
    String password = "";
    String url = "jdbc:mysql://localhost/" + dbName;
    public static final String TABLE_NAME="orderlist";
    public static int PER_SHRIT_PRICE=200;
    public static int PER_PANT_PRICE=300;
    public static int REGULAR_TYPE=500;
    public static int EMERGENCY_TYPE=1000;
    String buyerSerialNo,companyName,address,contactNo,orderSerialNo,rDate,dDate,itemType,itemSize,itemAmount
            ,orderTitle,orderType,orderStatus,totalBill,advance,due;
    int total;
    public GetOrder() {
        initComponents();
        getComoboxValue("orderList","orderSerialNo",CBorderSearch);
        getComoboxValue("buyer","companyName",CBbuyerName);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnUpdate = new javax.swing.JButton();
        btnView = new javax.swing.JButton();
        refreshLabel = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        labelHome = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        CBbuyerName = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        TFserialNo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TFname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TFaddress = new javax.swing.JTextField();
        TFcontactNo = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        TForderSerialNo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        CBitemType = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        TFamount = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        TForderTitle = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        CBorderType = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        CBsize = new javax.swing.JComboBox<>();
        btnBill = new javax.swing.JButton();
        TFtotalBill = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        TFadvance = new javax.swing.JTextField();
        btnDue = new javax.swing.JButton();
        TFdue = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        CBorderStatus = new javax.swing.JComboBox<>();
        measurment = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        CBorderSearch = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setLocation(new java.awt.Point(250, 20));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(45, 118, 232));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/icons8_Order_History_50px_1.png"))); // NOI18N
        jLabel15.setText("Order Widget");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 77, -1, -1));

        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/icons8_Delete32.png_32.png"))); // NOI18N
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                exitMousePressed(evt);
            }
        });
        jPanel1.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 10, -1, -1));

        jPanel2.setPreferredSize(new java.awt.Dimension(850, 463));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnUpdate.setBackground(new java.awt.Color(45, 118, 232));
        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/icons8_Update_User.png_16.png"))); // NOI18N
        btnUpdate.setText("Edit");
        btnUpdate.setBorder(null);
        btnUpdate.setIconTextGap(6);
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnView.setBackground(new java.awt.Color(45, 118, 232));
        btnView.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/icons8_View_All.png_16.png"))); // NOI18N
        btnView.setText("View All");
        btnView.setBorder(null);
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        refreshLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/icons8_Refresh-blue.png_32.png"))); // NOI18N
        refreshLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                refreshLabelMouseClicked(evt);
            }
        });

        btnSave.setBackground(new java.awt.Color(45, 118, 232));
        btnSave.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/icons8_Plus.png_16.png"))); // NOI18N
        btnSave.setText("Save");
        btnSave.setBorder(null);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(45, 118, 232));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/icons8_Cancel.png_16.png"))); // NOI18N
        jButton4.setText("Delete");
        jButton4.setBorder(null);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(refreshLabel)
                .addGap(43, 43, 43))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(refreshLabel)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 460, 490, 70));

        labelHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/icons8_Home_Page.png_32.png_32.png"))); // NOI18N
        labelHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelHomeMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                labelHomeMousePressed(evt);
            }
        });
        jPanel2.add(labelHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        jPanel4.setBackground(new java.awt.Color(153, 153, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        CBbuyerName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Buyer Name" }));
        CBbuyerName.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CBbuyerNameItemStateChanged(evt);
            }
        });

        jLabel1.setText("Buyer Serial No");

        jLabel2.setText("Buyer Name");

        TFname.setText(" ");

        jLabel3.setText("Address");

        jLabel4.setText("Contact No");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TFname)
                    .addComponent(CBbuyerName, 0, 246, Short.MAX_VALUE)
                    .addComponent(TFserialNo))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TFcontactNo, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TFaddress, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CBbuyerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TFserialNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(TFaddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TFname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(TFcontactNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 760, 120));

        jPanel5.setBackground(new java.awt.Color(153, 153, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel5.setText("Order Serial No");

        TForderSerialNo.setText("ORD-");

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel6.setText("Eg: ORD-XXXX ; Duplicate can't be inserted");

        jLabel7.setText("Item Type");

        CBitemType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Shirt", "Pant" }));

        jLabel8.setText("Item Amount");

        jLabel9.setText("Order Title");

        jLabel10.setText("Order Receive Date");

        jLabel11.setText("Order Delivery Date");

        jLabel12.setText("Order Type");

        CBorderType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Regular", "Emergency" }));

        jLabel13.setText("Item Size");

        CBsize.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "S", "M", "L" }));

        btnBill.setBackground(new java.awt.Color(45, 118, 232));
        btnBill.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBill.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/icons8_Money.png_16.png"))); // NOI18N
        btnBill.setText("Bill");
        btnBill.setBorder(null);
        btnBill.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBillMouseClicked(evt);
            }
        });
        btnBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBillActionPerformed(evt);
            }
        });

        TFtotalBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFtotalBillActionPerformed(evt);
            }
        });

        jLabel16.setText("Advance Payment");

        btnDue.setBackground(new java.awt.Color(45, 118, 232));
        btnDue.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/icons8_Money.png_16.png"))); // NOI18N
        btnDue.setText("Due Bill");
        btnDue.setBorder(null);
        btnDue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDueMouseClicked(evt);
            }
        });
        btnDue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDueActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel20.setText("Eg: Order of 'Item Amount' pieces 'Item type'");

        jLabel14.setText("Tk.");

        jLabel17.setText("Tk.");

        jPanel6.setBackground(new java.awt.Color(153, 153, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel18.setText("Order Status");

        CBorderStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Approved", "Delivered", "Delay Delivered", "Canceled", "" }));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CBorderStatus, 0, 116, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(CBorderStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        measurment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/icons8_Sewing_Tape_Measure.png_32.png_32.png"))); // NOI18N
        measurment.setText("\n");
        measurment.setToolTipText("Measurement");
        measurment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                measurmentMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel16)
                    .addComponent(btnDue, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TForderSerialNo, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(TFamount, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CBitemType, javax.swing.GroupLayout.Alignment.LEADING, 0, 86, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(CBsize, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(CBorderType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(measurment)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(btnBill, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TFtotalBill, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel14))
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE))
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TFdue, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TFadvance, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(TForderTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(jLabel20)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TForderSerialNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(CBitemType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(CBsize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(measurment))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(TFamount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(CBorderType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnBill, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TFtotalBill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(TForderTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(TFadvance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(TFdue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel17))
                            .addComponent(btnDue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 760, 260));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/icons8_Search-blue-16.png_16.png"))); // NOI18N
        jLabel19.setToolTipText("Search an Order");

        CBorderSearch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Order Serial No" }));
        CBorderSearch.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CBorderSearchItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CBorderSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CBorderSearch))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 20, 180, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMousePressed
        System.exit(0);
    }//GEN-LAST:event_exitMousePressed

    private void labelHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelHomeMouseClicked
       this.dispose();
       new Home().setVisible(true);
    }//GEN-LAST:event_labelHomeMouseClicked

    private void refreshLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refreshLabelMouseClicked
        refresh();
    }//GEN-LAST:event_refreshLabelMouseClicked

    private void labelHomeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelHomeMousePressed
       
    }//GEN-LAST:event_labelHomeMousePressed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        //new GetOrderViewAll().show();
    }//GEN-LAST:event_btnViewActionPerformed

    
   /*
       UPDATE
    */
    
    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
         try(Connection con = DriverManager.getConnection(url, user, password)){
             String serialNo=TFserialNo.getText();
             String companyName=TFserialNo.getText();
             String address=TFaddress.getText();
             String email =TFemail.getText();
             String contactNo=TFcontactNo.getText();
             String date=((JTextField)JentryDate.getDateEditor().getUiComponent()).getText();
             String query = "UPDATE buyer SET companyName='"
            +companyName+"',address='"+address+"',contactNo='"
            +contactNo+"',email='"
            +email+"',entryDate='"+date+"' where serialNo='"
            +serialNo+"';";
 
                     pst = con.prepareStatement(query);
                     
 
                 int rowsUpdated = pst.executeUpdate();
                 //pst.execute();
                 if (rowsUpdated > 0) {
                JOptionPane.showMessageDialog(null,"An existing user was updated successfully!");
                   }
         }catch (SQLException ex) {
            Logger.getLogger(GetOrder.class.getName()).log(Level.SEVERE, null, ex);
           
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void CBorderSearchItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CBorderSearchItemStateChanged
         try(Connection con = DriverManager.getConnection(url, user, password)){
             String searchQuery="SELECT * FROM "+TABLE_NAME+" WHERE orderSerialNo=?";
            
            pst=con.prepareStatement(searchQuery);
          
            pst.setString(1, CBorderSearch.getSelectedItem().toString());
            
           
            rs=pst.executeQuery();
  
             if(rs.next()){
                   String serialNo=rs.getString("serialNo");
                   TFserialNo.setText(serialNo);
               
                   String companyName = rs.getString("name");
                   TFname.setText(companyName);
                   
                   String address = rs.getString("address");
                   TFaddress.setText(address);
                   
                   String contactNo = rs.getString("contactNo");
                   TFcontactNo.setText(contactNo);
                   
                   String OrderserialNo=rs.getString("OrderSerialNo");
                   TForderSerialNo.setText(OrderserialNo);
                   String Date1 = rs.getString("receiveDate");
                   ((JTextField)receiveDate.getDateEditor().getUiComponent()).setText(Date1);
                   
                   String date = rs.getString("deliveryDate");
                   ((JTextField)deliveryDate.getDateEditor().getUiComponent()).setText(date);
                   
                   String itemAmount = rs.getString("itemAmount");
                   TFamount.setText(itemAmount);
                   
                   String title = rs.getString("orderTitle");
                   TForderTitle.setText(title);
                   
                   String totalBill = rs.getString("totalBill");
                   TFtotalBill.setText(totalBill);
                   
                   String advanceBill = rs.getString("advanceBill");
                   TFadvance.setText(advanceBill);
                   
                   String dueBill = rs.getString("dueBill");
                   TFdue.setText(dueBill);
                   
                   String itemType= rs.getString("itemType");
                   if(itemType=="Shirt"){
                       CBitemType.setSelectedItem(itemType);
                   }
                   else if(itemType=="Pant"){
                       CBitemType.setSelectedItem(itemType);
                   }
                   
                   String itemSize= rs.getString("itemSize");
                   if(itemSize=="S"){
                       CBsize.setSelectedItem(itemSize);
                   }
                   else if(itemSize=="M"){
                       CBsize.setSelectedItem(itemSize);
                   }
                   else{
                        CBsize.setSelectedItem("L");
                   }
                   
                   String orderType = rs.getString("orderType");
                    if(orderType=="Regular"){
                       CBsize.setSelectedItem(orderType);
                   }
                   else if(orderType=="Emergency"){
                       CBsize.setSelectedItem(orderType);
                   }
                    
                   String orderStatus = rs.getString("orderStatus");
                   switch(orderStatus){
                       case "Delay Delivered":
                            CBorderStatus.setSelectedItem(orderStatus);
                            break;
                       case "Approved":
                            CBorderStatus.setSelectedItem(orderStatus);
                            break;
                       case "Delivered":
                            CBorderStatus.setSelectedItem(orderStatus);
                            break;
                       case "Canceled":
                           CBorderStatus.setSelectedItem(orderStatus);
                            break;
                       default:
                           CBorderStatus.setSelectedItem("None");
                            break;
                   }
                   
                   
                   
                   
             }
         } catch (SQLException ex) {
            Logger.getLogger(GetOrder.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_CBorderSearchItemStateChanged

    private void measurmentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_measurmentMouseClicked
       String orderNo = TForderSerialNo.getText();
       String orderType = CBitemType.getSelectedItem().toString();
       String orderSize = CBsize.getSelectedItem().toString();
       new MeasuringTable(orderNo,orderType,orderSize).show();
   
       this.dispose();
    }//GEN-LAST:event_measurmentMouseClicked

    private void CBbuyerNameItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CBbuyerNameItemStateChanged
       try(Connection con = DriverManager.getConnection(url, user, password)){
             String searchQuery="SELECT * FROM buyer WHERE companyName=?";
            
            pst=con.prepareStatement(searchQuery);
          
            pst.setString(1, CBbuyerName.getSelectedItem().toString());
            
           
            rs=pst.executeQuery();
  
             if(rs.next()){
                   String serialNo=rs.getString("serialNo");
                   TFserialNo.setText(serialNo);
               
                   String companyName = rs.getString("companyName");
                   TFname.setText(companyName);
                   
                   String address = rs.getString("address");
                   TFaddress.setText(address);
                   
                   String contactNo = rs.getString("contactNo");
                   TFcontactNo.setText(contactNo);
                   
                
             }
         } catch (SQLException ex) {
            Logger.getLogger(GetOrder.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_CBbuyerNameItemStateChanged
    public void getAllFieldValue(){
             buyerSerialNo=TFserialNo.getText();
             companyName=TFserialNo.getText();
             address=TFaddress.getText();
             contactNo=TFcontactNo.getText();
             rDate=((JTextField)receiveDate.getDateEditor().getUiComponent()).getText();
             dDate=((JTextField)deliveryDate.getDateEditor().getUiComponent()).getText();
             orderSerialNo=TForderSerialNo.getText();
             orderTitle=TForderTitle.getText();
             orderType=CBorderType.getSelectedItem().toString();
             itemSize=CBsize.getSelectedItem().toString();
             itemType=CBitemType.getSelectedItem().toString();
             itemAmount=TFamount.getText();
             orderStatus=CBorderStatus.getSelectedItem().toString();
             totalBill=TFtotalBill.getText();
             due=TFdue.getText();
             advance=TFadvance.getText();
             
 }
    private void btnBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBillActionPerformed
                 getAllFieldValue();
                  int deliveryCharge;
                 /*int total = Integer.parseInt(totalBill);
                 int advaceBiill = Integer.parseInt(advance);
                 int dueBill = Integer.parseInt(due);*/
                 int amount = Integer.parseInt(itemAmount);
                 
                 if(orderType=="Regular"){
                     deliveryCharge=REGULAR_TYPE;
                 }
                 else{
                     deliveryCharge=EMERGENCY_TYPE;
                 }
                 if(itemType=="Shirt"){
                      total=amount*PER_SHRIT_PRICE +deliveryCharge;
                      this.TFtotalBill.setText(String.valueOf(total));
                 }
                 else{
                    total=amount*PER_PANT_PRICE + deliveryCharge;
                    this.TFtotalBill.setText(String.valueOf(total));
                 }
                //getTotal(total);
                
                 
    }//GEN-LAST:event_btnBillActionPerformed
   
    /*public int getTotal(int totalBill){
        return  totalBill;
    }*/
    private void btnBillMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBillMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBillMouseClicked

    private void btnDueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDueActionPerformed
        try{
            getAllFieldValue();
            int advancePayment = Integer.parseInt(advance);
            //totalint tb=getTotal(totalBill);
            int due=total-advancePayment;
            TFdue.setText(String.valueOf(due));
        }
        catch(NumberFormatException ex){
            Logger.getLogger(GetOrder.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnDueActionPerformed

    private void btnDueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDueMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDueMouseClicked

    private void TFtotalBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFtotalBillActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFtotalBillActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        try(Connection con = DriverManager.getConnection(url, user, password)){
                    String query = "INSERT INTO " +TABLE_NAME+" (orderSerialNo,serialNo,name,address,contactNo,itemType,itemSize,orderType,orderTitle,orderStatus,itemAmount,totalBill,advanceBill,dueBill,receiveDate,deliveryDate) VALUES (?, ?, ?, ?,?,?,?, ?, ?, ?,?,?,?,?,?,?)";
                     getAllFieldValue();
                     pst = con.prepareStatement(query);
                     pst.setString(1,orderSerialNo);
                     pst.setString(2,buyerSerialNo);
                     pst.setString(3,companyName);
                     pst.setString(4,address);
                     pst.setString(5,contactNo);
                     pst.setString(6,itemType);
                     pst.setString(7,itemSize);
                     pst.setString(8,orderType);
                     pst.setString(9,orderTitle);
                     pst.setString(10,orderStatus);
                     pst.setString(11,itemAmount);
                     pst.setString(12,totalBill);
                     pst.setString(13,advance);
                     pst.setString(14,due);
                     pst.setString(15,rDate);
                     pst.setString(16,dDate);
                     
                     int rowsInserted = pst.executeUpdate();
                     if (rowsInserted > 0) {
                     JOptionPane.showMessageDialog(null,"An order is inserted successfully!");
                 }
           
        } catch (SQLException ex) {
            final JPanel errorPanel = new JPanel();

            JOptionPane.showMessageDialog(errorPanel, "Duplicate order serial no can not be inserted", "Error", JOptionPane.ERROR_MESSAGE);
        
            Logger.getLogger(GetOrder.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSaveActionPerformed
    /*
         SEARCH
    */
    
    public void advanceSearch(String query){
         //try(Connection con = DriverManager.getConnection(url, user, password)){
          
                         
               /*pst=con.prepareStatement(query);
               pst.setString(1, TFsearch.getText());
               rs=pst.executeQuery();
               if(rs.next()){
                   String serialNo=rs.getString("serialNo");
                   TFserialNo.setText(serialNo);
               
                   
                  String companyName = rs.getString("companyName");
                   TFserialNo.setText(companyName);
                   
                   String address = rs.getString("address");
                   TFaddress.setText(address);
                   
                   String contactNo = rs.getString("contactNo");
                   TFcontactNo.setText(contactNo);
                   
                   String email = rs.getString("email");
                   TFemail.setText(email);
                   
                   String date = rs.getString("entryDate");
                   ((JTextField)JentryDate.getDateEditor().getUiComponent()).setText(date);
                   
              }
              
           
       } catch (SQLException ex) {
            Logger.getLogger(GetOrder.class.getName()).log(Level.SEVERE, null, ex);
            
        }*/
        
    }
    public ResultSet showSelectedInfo(JComboBox CBselect, String tableName,String columnName){
        
        try(Connection con = DriverManager.getConnection(url, user, password)){
            
            String id=CBselect.getSelectedItem().toString();
            
            String searchQuery="SELECT * FROM "+tableName+" WHERE "+columnName+"=?";
            
            pst=con.prepareStatement(searchQuery);
          
            pst.setString(1, CBselect.getSelectedItem().toString());
            
           
            rs=pst.executeQuery();
   
            
           } catch (SQLException ex) {
            Logger.getLogger(Payroll.class.getName()).log(Level.SEVERE, null, ex);
        }
        return rs;
        
    }
    public void getComoboxValue(String tableName,String columnName,JComboBox CBselect){
        try(Connection con = DriverManager.getConnection(url, user, password)){
            String query= "SELECT "+columnName+" FROM "+tableName;
            pst=con.prepareStatement(query);
            rs=pst.executeQuery();
            while(rs.next()){
                
              
              CBselect.addItem(rs.getString(columnName));
            }
            /*int totalItem=CBselect.getItemCount();
            System.out.println(totalItem);*/
            
            
            
        } catch (SQLException ex) {
            Logger.getLogger(Payroll.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public void refresh(){
       TFserialNo.setText("");
       TFserialNo.setText("");
       TFaddress.setText("");
       TFcontactNo.setText("");
       TFemail.setText("");
       ((JTextField)JentryDate.getDateEditor().getUiComponent()).setText("");
       TFsearch.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GetOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GetOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GetOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GetOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GetOrder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBbuyerName;
    private javax.swing.JComboBox<String> CBitemType;
    private javax.swing.JComboBox<String> CBorderSearch;
    private javax.swing.JComboBox<String> CBorderStatus;
    private javax.swing.JComboBox<String> CBorderType;
    private javax.swing.JComboBox<String> CBsize;
    private javax.swing.JTextField TFaddress;
    private javax.swing.JTextField TFadvance;
    private javax.swing.JTextField TFamount;
    private javax.swing.JTextField TFcontactNo;
    private javax.swing.JTextField TFdue;
    private javax.swing.JTextField TFname;
    private javax.swing.JTextField TForderSerialNo;
    private javax.swing.JTextField TForderTitle;
    private javax.swing.JTextField TFserialNo;
    private javax.swing.JTextField TFtotalBill;
    private javax.swing.JButton btnBill;
    private javax.swing.JButton btnDue;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnView;
    private javax.swing.JLabel exit;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel labelHome;
    private javax.swing.JLabel measurment;
    private javax.swing.JLabel refreshLabel;
    // End of variables declaration//GEN-END:variables
}
