/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;


import javax.swing.JPanel;

/**
 *
 * @author Purba
 */

public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    Login login = new Login();
    public Home() {
        initComponents();
        loggedUsernameLabel.setText(String.valueOf(login.loggedUserName).toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPanel = new javax.swing.JPanel();
        headerPanel = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        statisticPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        employeePanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        buyerPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        orderPanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        purchasePanel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        paymentPanel = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        vendorPanel = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        updateProfilePanel = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        logout = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        loggedUsernameLabel = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(250, 20));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(860, 650));

        backgroundPanel.setBackground(new java.awt.Color(255, 255, 255));
        backgroundPanel.setMinimumSize(new java.awt.Dimension(860, 600));
        backgroundPanel.setPreferredSize(new java.awt.Dimension(854, 600));
        backgroundPanel.setLayout(null);

        headerPanel.setBackground(new java.awt.Color(45, 118, 232));
        headerPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerPanelMouseDragged(evt);
            }
        });
        headerPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerPanelMousePressed(evt);
            }
        });
        headerPanel.setLayout(null);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Management System");
        headerPanel.add(jLabel13);
        jLabel13.setBounds(140, 120, 146, 17);

        exit.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        exit.setForeground(new java.awt.Color(255, 255, 255));
        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/icons8_Delete32.png_32.png"))); // NOI18N
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                exitMousePressed(evt);
            }
        });
        headerPanel.add(exit);
        exit.setBounds(820, 0, 50, 50);

        jLabel15.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText(" Garments");
        headerPanel.add(jLabel15);
        jLabel15.setBounds(130, 80, 134, 29);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/Sewing_Machine_100px.png"))); // NOI18N
        headerPanel.add(jLabel14);
        jLabel14.setBounds(30, 50, 90, 100);

        backgroundPanel.add(headerPanel);
        headerPanel.setBounds(0, 0, 880, 240);

        statisticPanel.setBackground(java.awt.SystemColor.controlHighlight);
        statisticPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                statisticPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                statisticPanelMouseExited(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(45, 118, 232));
        jLabel2.setText("Statistic");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/icons8_Combo_Chart_50px.png"))); // NOI18N

        javax.swing.GroupLayout statisticPanelLayout = new javax.swing.GroupLayout(statisticPanel);
        statisticPanel.setLayout(statisticPanelLayout);
        statisticPanelLayout.setHorizontalGroup(
            statisticPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statisticPanelLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(statisticPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        statisticPanelLayout.setVerticalGroup(
            statisticPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statisticPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        backgroundPanel.add(statisticPanel);
        statisticPanel.setBounds(460, 470, 149, 120);

        employeePanel.setBackground(java.awt.SystemColor.controlHighlight);
        employeePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                employeePanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                employeePanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                employeePanelMousePressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(45, 118, 232));
        jLabel3.setText("Employees");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/icons8_Employee_50px.png"))); // NOI18N

        javax.swing.GroupLayout employeePanelLayout = new javax.swing.GroupLayout(employeePanel);
        employeePanel.setLayout(employeePanelLayout);
        employeePanelLayout.setHorizontalGroup(
            employeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(employeePanelLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(employeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        employeePanelLayout.setVerticalGroup(
            employeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(employeePanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        backgroundPanel.add(employeePanel);
        employeePanel.setBounds(110, 320, 152, 120);

        buyerPanel.setBackground(java.awt.SystemColor.controlHighlight);
        buyerPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buyerPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buyerPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buyerPanelMousePressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(45, 118, 232));
        jLabel5.setText("Buyers");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/group_52px.png"))); // NOI18N

        javax.swing.GroupLayout buyerPanelLayout = new javax.swing.GroupLayout(buyerPanel);
        buyerPanel.setLayout(buyerPanelLayout);
        buyerPanelLayout.setHorizontalGroup(
            buyerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buyerPanelLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(buyerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        buyerPanelLayout.setVerticalGroup(
            buyerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buyerPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        backgroundPanel.add(buyerPanel);
        buyerPanel.setBounds(290, 320, 140, 120);

        orderPanel.setBackground(java.awt.SystemColor.controlHighlight);
        orderPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                orderPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                orderPanelMouseExited(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(45, 118, 232));
        jLabel7.setText("Order");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/icons8_Order_History_50px.png"))); // NOI18N

        javax.swing.GroupLayout orderPanelLayout = new javax.swing.GroupLayout(orderPanel);
        orderPanel.setLayout(orderPanelLayout);
        orderPanelLayout.setHorizontalGroup(
            orderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(orderPanelLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(orderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        orderPanelLayout.setVerticalGroup(
            orderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(orderPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        backgroundPanel.add(orderPanel);
        orderPanel.setBounds(460, 320, 140, 120);

        purchasePanel.setBackground(java.awt.SystemColor.controlHighlight);
        purchasePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                purchasePanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                purchasePanelMouseExited(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(45, 118, 232));
        jLabel9.setText("Purchase");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/icons8_Purchase_Order_52px.png"))); // NOI18N

        javax.swing.GroupLayout purchasePanelLayout = new javax.swing.GroupLayout(purchasePanel);
        purchasePanel.setLayout(purchasePanelLayout);
        purchasePanelLayout.setHorizontalGroup(
            purchasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(purchasePanelLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(purchasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        purchasePanelLayout.setVerticalGroup(
            purchasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(purchasePanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        backgroundPanel.add(purchasePanel);
        purchasePanel.setBounds(110, 470, 152, 120);

        paymentPanel.setBackground(java.awt.SystemColor.controlHighlight);
        paymentPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                paymentPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                paymentPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                paymentPanelMousePressed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(45, 118, 232));
        jLabel11.setText("Payroll");

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/icons8_Cash_in_Hand_48px.png"))); // NOI18N

        javax.swing.GroupLayout paymentPanelLayout = new javax.swing.GroupLayout(paymentPanel);
        paymentPanel.setLayout(paymentPanelLayout);
        paymentPanelLayout.setHorizontalGroup(
            paymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paymentPanelLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(paymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        paymentPanelLayout.setVerticalGroup(
            paymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paymentPanelLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addContainerGap())
        );

        backgroundPanel.add(paymentPanel);
        paymentPanel.setBounds(290, 470, 140, 120);

        vendorPanel.setBackground(java.awt.SystemColor.controlHighlight);
        vendorPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                vendorPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                vendorPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                vendorPanelMousePressed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(45, 118, 232));
        jLabel16.setText("Vendors");

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/icons8_Supplier_50px.png"))); // NOI18N

        javax.swing.GroupLayout vendorPanelLayout = new javax.swing.GroupLayout(vendorPanel);
        vendorPanel.setLayout(vendorPanelLayout);
        vendorPanelLayout.setHorizontalGroup(
            vendorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vendorPanelLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(vendorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        vendorPanelLayout.setVerticalGroup(
            vendorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vendorPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        backgroundPanel.add(vendorPanel);
        vendorPanel.setBounds(640, 320, 149, 120);

        updateProfilePanel.setBackground(java.awt.SystemColor.controlHighlight);
        updateProfilePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                updateProfilePanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                updateProfilePanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                updateProfilePanelMousePressed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(45, 118, 232));
        jLabel18.setText("Update Profile");

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/icons8_Registration_48px_1.png"))); // NOI18N

        javax.swing.GroupLayout updateProfilePanelLayout = new javax.swing.GroupLayout(updateProfilePanel);
        updateProfilePanel.setLayout(updateProfilePanelLayout);
        updateProfilePanelLayout.setHorizontalGroup(
            updateProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateProfilePanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel18)
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, updateProfilePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addGap(43, 43, 43))
        );
        updateProfilePanelLayout.setVerticalGroup(
            updateProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateProfilePanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        backgroundPanel.add(updateProfilePanel);
        updateProfilePanel.setBounds(640, 470, 156, 120);

        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/icons8_Logout_Rounded_Left.png_32.png"))); // NOI18N
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });
        backgroundPanel.add(logout);
        logout.setBounds(790, 240, 32, 40);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(45, 118, 232));
        jLabel20.setText("Log Out");
        backgroundPanel.add(jLabel20);
        jLabel20.setBounds(780, 280, 60, 15);

        loggedUsernameLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        loggedUsernameLabel.setForeground(new java.awt.Color(45, 118, 232));
        backgroundPanel.add(loggedUsernameLabel);
        loggedUsernameLabel.setBounds(60, 260, 90, 30);

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/icons8_Male_User.png_32.png"))); // NOI18N
        backgroundPanel.add(jLabel21);
        jLabel21.setBounds(20, 260, 32, 32);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 880, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMousePressed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitMousePressed

    private void employeePanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_employeePanelMouseEntered
        // TODO add your handling code here:
        setColor(employeePanel);
    }//GEN-LAST:event_employeePanelMouseEntered

    private void employeePanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_employeePanelMouseExited
        // TODO add your handling code here:
        resetColor(employeePanel);
    }//GEN-LAST:event_employeePanelMouseExited
     
    
    
    
    int xx,xy;
    private void headerPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerPanelMousePressed
        // TODO add your handling code here:
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_headerPanelMousePressed

    private void headerPanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerPanelMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);  
    }//GEN-LAST:event_headerPanelMouseDragged

    private void buyerPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buyerPanelMouseEntered
        // TODO add your handling code here:
        setColor(buyerPanel);
    }//GEN-LAST:event_buyerPanelMouseEntered

    private void buyerPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buyerPanelMouseExited
        // TODO add your handling code here:
        resetColor(buyerPanel);
    }//GEN-LAST:event_buyerPanelMouseExited

    private void orderPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orderPanelMouseEntered
        // TODO add your handling code here
        setColor(orderPanel);
    }//GEN-LAST:event_orderPanelMouseEntered

    private void orderPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orderPanelMouseExited
        // TODO add your handling code here:
        resetColor(orderPanel);
    }//GEN-LAST:event_orderPanelMouseExited

    private void purchasePanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_purchasePanelMouseEntered
        // TODO add your handling code here:
        setColor(purchasePanel);
    }//GEN-LAST:event_purchasePanelMouseEntered

    private void purchasePanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_purchasePanelMouseExited
        // TODO add your handling code here:
        resetColor(purchasePanel);
        
    }//GEN-LAST:event_purchasePanelMouseExited

    private void paymentPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paymentPanelMouseEntered
        // TODO add your handling code here:
        setColor(paymentPanel);
    }//GEN-LAST:event_paymentPanelMouseEntered

    private void paymentPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paymentPanelMouseExited
        // TODO add your handling code here:
        resetColor(paymentPanel);
    }//GEN-LAST:event_paymentPanelMouseExited

    private void statisticPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_statisticPanelMouseEntered
        // TODO add your handling code here:
        setColor(statisticPanel);
    }//GEN-LAST:event_statisticPanelMouseEntered

    private void statisticPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_statisticPanelMouseExited
        // TODO add your handling code here:
        resetColor(statisticPanel);
    }//GEN-LAST:event_statisticPanelMouseExited

    private void employeePanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_employeePanelMousePressed
        // TODO add your handling code here:
        this.dispose();
        new Employee().show();
    }//GEN-LAST:event_employeePanelMousePressed

    private void buyerPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buyerPanelMousePressed
        // TODO add your handling code here:
        this.dispose();
        new Buyer().show();
    }//GEN-LAST:event_buyerPanelMousePressed

    private void vendorPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vendorPanelMouseEntered
        setColor(vendorPanel);
    }//GEN-LAST:event_vendorPanelMouseEntered

    private void vendorPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vendorPanelMouseExited
        resetColor(vendorPanel);
    }//GEN-LAST:event_vendorPanelMouseExited

    private void vendorPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vendorPanelMousePressed
         this.dispose();
        new Vendor().show();
    }//GEN-LAST:event_vendorPanelMousePressed

    private void updateProfilePanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateProfilePanelMouseEntered
       setColor(updateProfilePanel);
    }//GEN-LAST:event_updateProfilePanelMouseEntered

    private void updateProfilePanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateProfilePanelMouseExited
         resetColor(updateProfilePanel);
    }//GEN-LAST:event_updateProfilePanelMouseExited

    private void updateProfilePanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateProfilePanelMousePressed
        this.dispose();
        new UpdateProfile().getInfo();
         new UpdateProfile().show();
    }//GEN-LAST:event_updateProfilePanelMousePressed

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        this.dispose();
        new Login().setVisible(true);
    }//GEN-LAST:event_logoutMouseClicked

    private void paymentPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paymentPanelMousePressed
        this.dispose();
        new Payroll().show();
    }//GEN-LAST:event_paymentPanelMousePressed
 public void setColor(JPanel panel)
 {
     panel.setBackground(new java.awt.Color(197, 197, 197));
 }
 
 public void resetColor(JPanel panel)
 {
     panel.setBackground(new java.awt.Color(240,240,240));
 }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JPanel buyerPanel;
    private javax.swing.JPanel employeePanel;
    private javax.swing.JLabel exit;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel loggedUsernameLabel;
    private javax.swing.JLabel logout;
    private javax.swing.JPanel orderPanel;
    private javax.swing.JPanel paymentPanel;
    private javax.swing.JPanel purchasePanel;
    private javax.swing.JPanel statisticPanel;
    private javax.swing.JPanel updateProfilePanel;
    private javax.swing.JPanel vendorPanel;
    // End of variables declaration//GEN-END:variables
}
