/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import javax.swing.JTextField;

/**
 *
 * @author purba
 */
public class MeasuringTable extends javax.swing.JFrame {

    String orderNo,orderType,orderSize;
    public MeasuringTable() {
        initComponents();
    }
    public MeasuringTable(String orderNo,String orderType,String orderSize ) {
       
        initComponents();
        this.orderNo = orderNo;
        this.orderType =  orderType;
        this.orderSize=orderSize;
        TForderSerialNo.setText(orderNo);
        CBorderType.setSelectedItem(orderType);
         if((CBorderType.getSelectedIndex()==0)){
           CBorderSize.setSelectedItem(orderSize);
        }
         else if(CBorderType.getSelectedIndex()==1){
            CBpantOrderSize.setSelectedItem(orderSize);
        }
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        exitLabel = new javax.swing.JLabel();
        getPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        TForderSerialNo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        CBorderType = new javax.swing.JComboBox<>();
        pantPanel = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        CBpantOrderSize = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        TFpantWaist = new javax.swing.JTextField();
        TFpantHip = new javax.swing.JTextField();
        CBhem = new javax.swing.JTextField();
        CBout = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        shirtPanel = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        CBorderSize = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        TFcollar1 = new javax.swing.JTextField();
        TFchest1 = new javax.swing.JTextField();
        TFwaist1 = new javax.swing.JTextField();
        TFbottom1 = new javax.swing.JTextField();
        TFshoulder1 = new javax.swing.JTextField();
        TFsleeve1 = new javax.swing.JTextField();
        TFback1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setLocation(new java.awt.Point(250, 20));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(45, 118, 232));

        jLabel15.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/group_52px_1.png"))); // NOI18N
        jLabel15.setText("Measurement Chart");

        exitLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/icons8_Delete32.png_32.png"))); // NOI18N
        exitLabel.setToolTipText("");
        exitLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabel15)
                .addContainerGap(510, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exitLabel)
                .addGap(42, 42, 42))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(exitLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 160));

        jLabel2.setText("Order Serial No");

        jLabel3.setText("Order Type");

        CBorderType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Shirt", "Pant", " " }));
        CBorderType.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CBorderTypeItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout getPanelLayout = new javax.swing.GroupLayout(getPanel);
        getPanel.setLayout(getPanelLayout);
        getPanelLayout.setHorizontalGroup(
            getPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(getPanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(getPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(getPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TForderSerialNo)
                    .addComponent(CBorderType, 0, 193, Short.MAX_VALUE))
                .addContainerGap())
        );
        getPanelLayout.setVerticalGroup(
            getPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(getPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(getPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TForderSerialNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(getPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(CBorderType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(getPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 380, 90));

        pantPanel.setBackground(new java.awt.Color(153, 153, 255));
        pantPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "For Pant", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jLabel12.setText("Size");

        CBpantOrderSize.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "S", "M", "L", " " }));

        jLabel13.setText("Waist (cm)");

        jLabel14.setText("Hip (cm)");

        jLabel16.setText("Hem (cm)");

        jLabel17.setText("Outseam (cm)");

        jButton1.setBackground(new java.awt.Color(45, 118, 232));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/icons8_Checkmark.png_16.png"))); // NOI18N
        jButton1.setText("OK");
        jButton1.setBorder(null);

        jButton2.setBackground(new java.awt.Color(45, 118, 232));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/icons8_View_All.png_16.png"))); // NOI18N
        jButton2.setText("View ");
        jButton2.setBorder(null);

        javax.swing.GroupLayout pantPanelLayout = new javax.swing.GroupLayout(pantPanel);
        pantPanel.setLayout(pantPanelLayout);
        pantPanelLayout.setHorizontalGroup(
            pantPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pantPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pantPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pantPanelLayout.createSequentialGroup()
                        .addGroup(pantPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pantPanelLayout.createSequentialGroup()
                                .addGroup(pantPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14))
                                .addGap(37, 37, 37)
                                .addGroup(pantPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TFpantWaist)
                                    .addComponent(TFpantHip, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(CBpantOrderSize, 0, 71, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pantPanelLayout.createSequentialGroup()
                                .addGroup(pantPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel17))
                                .addGap(18, 18, 18)
                                .addGroup(pantPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CBhem)
                                    .addComponent(CBout))))
                        .addGap(0, 6, Short.MAX_VALUE))
                    .addGroup(pantPanelLayout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pantPanelLayout.setVerticalGroup(
            pantPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pantPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pantPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CBpantOrderSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pantPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(TFpantWaist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pantPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(TFpantHip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pantPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(CBhem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pantPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(CBout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(pantPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(120, 120, 120))
        );

        getContentPane().add(pantPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 310, 200, 350));

        shirtPanel.setBackground(new java.awt.Color(153, 153, 255));
        shirtPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "For Shirt", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        shirtPanel.setForeground(new java.awt.Color(255, 255, 255));

        jLabel18.setText("Size");

        CBorderSize.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "S", "M", "L", " " }));

        jLabel19.setText("Collar (cm)");

        jLabel20.setText("Chest (cm)");

        jLabel21.setText("Waist (cm)");

        jLabel22.setText("Bottom (cm)");

        jLabel23.setText("Shoulder (cm)");

        jLabel24.setText("Lenght of Sleeve (cm)");

        jLabel25.setText("Back (cm)");

        jButton3.setBackground(new java.awt.Color(45, 118, 232));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/icons8_View_All.png_16.png"))); // NOI18N
        jButton3.setText("View ");
        jButton3.setBorder(null);

        jButton4.setBackground(new java.awt.Color(45, 118, 232));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/icons8_Checkmark.png_16.png"))); // NOI18N
        jButton4.setText("OK");
        jButton4.setBorder(null);

        javax.swing.GroupLayout shirtPanelLayout = new javax.swing.GroupLayout(shirtPanel);
        shirtPanel.setLayout(shirtPanelLayout);
        shirtPanelLayout.setHorizontalGroup(
            shirtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(shirtPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(shirtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22)
                    .addComponent(jLabel23)
                    .addComponent(jLabel24)
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(shirtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(TFback1)
                    .addComponent(TFsleeve1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TFshoulder1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TFbottom1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CBorderSize, javax.swing.GroupLayout.Alignment.LEADING, 0, 111, Short.MAX_VALUE)
                    .addComponent(TFwaist1)
                    .addComponent(TFchest1)
                    .addComponent(TFcollar1, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(18, 18, 18)
                .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        shirtPanelLayout.setVerticalGroup(
            shirtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(shirtPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(shirtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CBorderSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(shirtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(TFcollar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(shirtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TFchest1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(shirtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(TFwaist1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(shirtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(TFbottom1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(shirtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TFshoulder1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(shirtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(TFsleeve1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(shirtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(shirtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel25)
                        .addComponent(TFback1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(660, 660, 660))
        );

        getContentPane().add(shirtPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, 440, 350));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/icons8_Home_Page.png_32.png_32.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLabelMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitLabelMouseClicked

    private void CBorderTypeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CBorderTypeItemStateChanged
       
      
        
    }//GEN-LAST:event_CBorderTypeItemStateChanged

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        this.dispose();
        new GetOrder().show();
    }//GEN-LAST:event_jLabel1MouseClicked
 public void getAllFieldValue(){
             buyerSerialNo=TFserialNo.getText();
             companyName=TFserialNo.getText();
             address=TFaddress.getText();
             contactNo=TFcontactNo.getText();
             rDate=((JTextField)receiveDate.getDateEditor().getUiComponent()).getText();
             dDate=((JTextField)deliveryDate.getDateEditor().getUiComponent()).getText();
             orderSerialNo=TForderSerialNo.getText();
             orderTitle=TForderTitle.getText();
             orderType=CBorderType.getSelectedItem().toString();
             itemSize=CBsize.getSelectedItem().toString();
             itemType=CBitemType.getSelectedItem().toString();
             itemAmount=TFamount.getText();
             orderStatus=CBorderStatus.getSelectedItem().toString();
             totalBill=TFtotalBill.getText();
             due=TFdue.getText();
             advance=TFadvance.getText();
             
 }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MeasuringTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MeasuringTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MeasuringTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MeasuringTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MeasuringTable().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CBhem;
    private javax.swing.JComboBox<String> CBorderSize;
    private javax.swing.JComboBox<String> CBorderType;
    private javax.swing.JTextField CBout;
    private javax.swing.JComboBox<String> CBpantOrderSize;
    private javax.swing.JTextField TFback1;
    private javax.swing.JTextField TFbottom1;
    private javax.swing.JTextField TFchest1;
    private javax.swing.JTextField TFcollar1;
    private javax.swing.JTextField TForderSerialNo;
    private javax.swing.JTextField TFpantHip;
    private javax.swing.JTextField TFpantWaist;
    private javax.swing.JTextField TFshoulder1;
    private javax.swing.JTextField TFsleeve1;
    private javax.swing.JTextField TFwaist1;
    private javax.swing.JLabel exitLabel;
    private javax.swing.JPanel getPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel pantPanel;
    private javax.swing.JPanel shirtPanel;
    // End of variables declaration//GEN-END:variables
}
