/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Font;
import java.awt.Image;

import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;

import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;


/**
 *
 * @author purba
 */
public class Payroll extends javax.swing.JFrame {

    FileInputStream fis;
    PreparedStatement pst = null;
    ResultSet rs = null;
    String dbName = "gmsDB";
    String user = "root";
    String password = "";
    byte[] employeeImage=null;
    byte[] updateImg=null;
    String url = "jdbc:mysql://localhost/" + dbName;
    public static final String TABLE_NAME="employee";
    public static final int PER_HOUR_OVERTIME_VALUE=300;
    PdfPCell cell;
    public Payroll() {
        initComponents();
       /*CBmonth.setSelectedItem("Select A Month");
       CBtype.setSelectedItem("Select A Type");
       CBreason.setSelectedItem("Select A Cause");*/
       getComoboxValue();
        TFhour.setText("0");
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        CBtype = new javax.swing.JComboBox<>();
        TFhour = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        CBreason = new javax.swing.JComboBox<>();
        TFamount = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        dynamicButtonAdd = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        TFtotalSalary = new javax.swing.JTextField();
        btnCalculate = new javax.swing.JButton();
        btnSalarySlip = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        TFmedical = new javax.swing.JTextField();
        TFbonus = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        TFother = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        TFserialNo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TFname = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        TFsalary = new javax.swing.JTextField();
        TFrank = new javax.swing.JTextField();
        TFworkingType = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        CBselect = new javax.swing.JComboBox<>();
        CBmonth = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        labelHome = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        labelViewALL = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setLocation(new java.awt.Point(250, 20));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(45, 118, 232));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/icons8_Payroll_50px.png"))); // NOI18N
        jLabel15.setText("Payroll");

        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/icons8_Delete32.png_32.png"))); // NOI18N
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabel15)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exit)
                .addGap(37, 37, 37))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(exit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel15)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(153, 153, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Over-Time", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));

        jLabel10.setText("Type");

        CBtype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Day Shift", "Night Shift" }));
        CBtype.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CBtypeItemStateChanged(evt);
            }
        });

        TFhour.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TFhourKeyTyped(evt);
            }
        });

        jLabel9.setText("Hours");

        jLabel13.setText("Per Hour=300 Taka");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9))
                .addGap(72, 72, 72)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel13)
                    .addComponent(TFhour)
                    .addComponent(CBtype, 0, 109, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CBtype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TFhour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(153, 153, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Deduction", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));
        jPanel5.setName(""); // NOI18N

        jLabel16.setText("Reason");

        jLabel17.setText("Amount");

        CBreason.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Irregular", "Late", "Other" }));

        TFamount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TFamountKeyTyped(evt);
            }
        });

        jLabel18.setText("Taka");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CBreason, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TFamount, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(4, 4, 4)
                .addComponent(jLabel18)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(CBreason, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TFamount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel18)))
                .addContainerGap())
        );

        jLabel19.setText("Total Monthly Salary ");

        btnCalculate.setBackground(new java.awt.Color(45, 118, 232));
        btnCalculate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCalculate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/icons8_Calculatonr.png_16.png"))); // NOI18N
        btnCalculate.setText("Calculate");
        btnCalculate.setBorder(null);
        btnCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateActionPerformed(evt);
            }
        });

        btnSalarySlip.setBackground(new java.awt.Color(45, 118, 232));
        btnSalarySlip.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSalarySlip.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/icons8_PDF.png_16.png"))); // NOI18N
        btnSalarySlip.setText("Salary Slip");
        btnSalarySlip.setBorder(null);
        btnSalarySlip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalarySlipActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dynamicButtonAddLayout = new javax.swing.GroupLayout(dynamicButtonAdd);
        dynamicButtonAdd.setLayout(dynamicButtonAddLayout);
        dynamicButtonAddLayout.setHorizontalGroup(
            dynamicButtonAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dynamicButtonAddLayout.createSequentialGroup()
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TFtotalSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(btnCalculate, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalarySlip, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        dynamicButtonAddLayout.setVerticalGroup(
            dynamicButtonAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dynamicButtonAddLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dynamicButtonAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TFtotalSalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(btnCalculate, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalarySlip, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(153, 153, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Extra", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));

        jLabel2.setText("Medical");

        jLabel8.setText("Bonus");

        TFmedical.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TFmedicalKeyTyped(evt);
            }
        });

        TFbonus.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TFbonusKeyTyped(evt);
            }
        });

        jLabel11.setText("Other");

        TFother.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TFotherKeyTyped(evt);
            }
        });

        jLabel12.setText("Taka");

        jLabel20.setText("Taka");

        jLabel21.setText("Taka");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(31, 31, 31)
                        .addComponent(TFmedical))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TFbonus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TFother, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(4, 4, 4)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TFmedical, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(27, 27, 27)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(TFbonus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addGap(31, 31, 31)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(TFother, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(153, 153, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setText("Employee ID");

        jLabel5.setText("Employee Name");

        jLabel6.setText("Working Type");

        jLabel7.setText("Rank");

        jLabel1.setText("Basic Salary");

        jLabel4.setText("Taka");

        CBselect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Employee ID" }));
        CBselect.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CBselectItemStateChanged(evt);
            }
        });
        CBselect.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CBselectMouseClicked(evt);
            }
        });

        CBmonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Month", "January", "February", "March", "April ", "May", "June", "July", "August ", "September", "October", "November", "December" }));
        CBmonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBmonthActionPerformed(evt);
            }
        });

        jLabel22.setText("Format-EXXX ; Duplicate value can not be inserted");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel1))
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(TFsalary, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(CBselect, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CBmonth, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(TFserialNo, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(TFrank, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                        .addComponent(TFworkingType, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(TFname, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(275, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CBselect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CBmonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TFserialNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TFname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TFworkingType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(TFrank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TFsalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        labelHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/icons8_Home_Page.png_32.png_32.png"))); // NOI18N
        labelHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelHomeMouseClicked(evt);
            }
        });

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/icons8_Refresh-blue.png_32.png"))); // NOI18N
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });

        labelViewALL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/icons8_View_Details.png_32.png"))); // NOI18N
        labelViewALL.setToolTipText("View");
        labelViewALL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelViewALLMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(269, 269, 269)
                .addComponent(dynamicButtonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelHome, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelViewALL, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel14))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(156, 156, 156))
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelViewALL)
                    .addComponent(labelHome)
                    .addComponent(jLabel14))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dynamicButtonAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
       System.exit(0);
    }//GEN-LAST:event_exitMouseClicked
    
    private void labelHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelHomeMouseClicked
        this.dispose();
        new Home().show();
    }//GEN-LAST:event_labelHomeMouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
       refresh();
    }//GEN-LAST:event_jLabel14MouseClicked
    int xx,xy;
    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
       int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy); 
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        // TODO add your handling code here:
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void CBselectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CBselectMouseClicked
       //showSelectedInfo();
    }//GEN-LAST:event_CBselectMouseClicked

    private void CBselectItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CBselectItemStateChanged
        
        showSelectedInfo();
        
        if(CBselect.getSelectedIndex()==0){
              TFserialNo.setText("");
              TFname.setText("");
              TFrank.setText("");
              TFworkingType.setText("");
              TFsalary.setText("");
        }
        
    }//GEN-LAST:event_CBselectItemStateChanged

    private void CBmonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBmonthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBmonthActionPerformed

    private void btnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateActionPerformed
       try(Connection con = DriverManager.getConnection(url, user, password)){
           int totalSalary,basicSalary,hour,amount,medical,bonus,other;
           basicSalary=Integer.parseInt(TFsalary.getText());
           hour=Integer.parseInt(TFhour.getText());
           amount=Integer.parseInt(TFamount.getText());
           medical=Integer.parseInt(TFmedical.getText());
           bonus=Integer.parseInt(TFbonus.getText());
           other=Integer.parseInt(TFother.getText());
           
           /*
               calculation
           */
           totalSalary= (basicSalary +((hour*PER_HOUR_OVERTIME_VALUE)+medical+bonus+other))-amount;
           TFtotalSalary.setText(String.valueOf(totalSalary));
           
           insertPayroll();
           
       }   catch (SQLException ex) {
            Logger.getLogger(Payroll.class.getName()).log(Level.SEVERE, null, ex);
        }
      
       
    }//GEN-LAST:event_btnCalculateActionPerformed
      public void insertPayroll(){
           try(Connection con = DriverManager.getConnection(url, user, password)){
                    String query = "INSERT INTO allowance (serialNo,name,workingType,rank,month,bSalary,type,hour,reason,amount,totalSalary,medical,bonus,other) VALUES (?, ?, ?, ?,?,?,?, ?, ?, ?,?,?,?,?)";
 
                     pst = con.prepareStatement(query);
                     pst.setString(1, TFserialNo.getText());
                     pst.setString(2, TFname.getText());
                     pst.setString(3, TFworkingType.getText());
                     pst.setString(4, TFrank.getText());
                     //int no=Integer.parseInt(TFcontactNo.getText());
                     String month=CBmonth.getSelectedItem().toString();
                     pst.setString(5, month);
                     pst.setString(6, TFsalary.getText());
                     String type=CBmonth.getSelectedItem().toString();
                     pst.setString(7,type);
                  
                     pst.setString(8, TFhour.getText());
                     String reason=CBmonth.getSelectedItem().toString();
                     pst.setString(9, reason);
                     pst.setString(10, TFamount.getText());
                     pst.setString(11, TFtotalSalary.getText());
                     pst.setString(12, TFmedical.getText());
                     pst.setString(13, TFbonus.getText());
                     pst.setString(14, TFother.getText());
                     
                     int rowsInserted = pst.executeUpdate();
                     if (rowsInserted > 0) {
                     JOptionPane.showMessageDialog(null,"Payroll is inserted successfully!");
                 }
           
        } catch (SQLException ex) {
            Logger.getLogger(Payroll.class.getName()).log(Level.SEVERE, null, ex);
        }
       }
    private void labelViewALLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelViewALLMouseClicked
        this.dispose();
        new PayrollViewAll().show();
    }//GEN-LAST:event_labelViewALLMouseClicked

    private void btnSalarySlipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalarySlipActionPerformed
        //if(!TFserialNo.getText().isEmpty()){
        
            String serialNo=TFserialNo.getText();
            String name=TFname.getText();
            JFileChooser chooser = new JFileChooser();
            chooser.setSelectedFile(new File(serialNo+"-"+name+"-Salary Slip"+".pdf"));
            int dialogResult=chooser.showSaveDialog(null);
            if(dialogResult==JFileChooser.APPROVE_OPTION){
                String filePath = chooser.getSelectedFile().getPath();
                Document document = new Document();
                try {
                    
                    PdfWriter writer = PdfWriter.getInstance(document,new FileOutputStream(filePath));
                    document.open();
                    document.add(new Paragraph("Garments Management System",FontFactory.getFont(FontFactory.TIMES_BOLD, 20,Font.BOLD)));
                    document.add(new Paragraph(new Date().toString()));
                    document.add(new Paragraph("____________________________________________________________________________\n\n"));
                    document.add(new Paragraph("Employee ID: "+serialNo+"\nEmployee Name: "+name+"\nRank: "+TFrank.getText()+"\nWorking Type: "+TFworkingType.getText()+"\n",FontFactory.getFont(FontFactory.TIMES, 14,Font.PLAIN)));
                    document.add(new Paragraph("\n____________________________________________________________________________\n")); 
                    document.add(new Paragraph("Monthly Salary Slip\n\n",FontFactory.getFont(FontFactory.TIMES_BOLD, 20,Font.BOLD)));
                    document.add(new Paragraph("Month:"+CBmonth.getSelectedItem().toString()+"\n\n",FontFactory.getFont(FontFactory.TIMES, 14,Font.BOLD)));
                    PdfPTable table = new PdfPTable(5);
                     
                    table.addCell("Basic Salary");
                    table.addCell("Medical Expense");
                    table.addCell("Bonus");
                    table.addCell("Over-Time");
                    table.addCell("Others");
                    table.addCell(TFsalary.getText()+" Tk");
                    table.addCell(TFmedical.getText()+" Tk");
                    table.addCell(TFbonus.getText()+" Tk");
                    int overTime=Integer.parseInt(TFhour.getText())* PER_HOUR_OVERTIME_VALUE;
                    table.addCell(String.valueOf(overTime)+" Tk");
                    table.addCell(TFother.getText()+" Tk");
                    
                    cell = new PdfPCell(new Phrase("Total Income"));
                    cell.setColspan(4);
                    table.addCell(cell);
                  
                    table.addCell(TFsalary.getText()+" Tk");
                    table.setHorizontalAlignment(Element.ALIGN_CENTER);
                    document.add(table);
                    
                    document.add(new Paragraph("\n\n"));
                    PdfPTable minus = new PdfPTable(3);
                    minus.addCell("Total Income");
                    minus.addCell("Deduction Cause");
                    minus.addCell("Amount");
                    minus.addCell(TFsalary.getText()+" Tk");                   
                    minus.addCell(CBreason.getSelectedItem().toString());
                    minus.addCell(TFamount.getText()+" Tk");
                    
                    cell = new PdfPCell(new Phrase("Received Payment"));
                    cell.setColspan(2);
                    minus.addCell(cell);
                    int payment= Integer.parseInt(TFsalary.getText())-Integer.parseInt(TFamount.getText());
                    minus.addCell(String.valueOf(payment)+" Tk");
                    document.add(minus);
                   document.add(new Paragraph("\n\n\n\n\n____________________________________________________________________________\n")); 
                    
                    document.close();
                    
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(Payroll.class.getName()).log(Level.SEVERE, null, ex);
                } catch (DocumentException ex) {
                    Logger.getLogger(Payroll.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            //}
            
            
            
        }  
        else{
             JOptionPane.showMessageDialog(null,"Calculate First");
        }
            
            
        
    }//GEN-LAST:event_btnSalarySlipActionPerformed

    private void TFhourKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFhourKeyTyped
        char c=evt.getKeyChar();
        if( ! (Character.isDigit(c))){
          getToolkit().beep();
          evt.consume();
      }
    }//GEN-LAST:event_TFhourKeyTyped

    private void TFamountKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFamountKeyTyped
       char c=evt.getKeyChar();
        if( ! (Character.isDigit(c))){
          getToolkit().beep();
          evt.consume();
      }
    }//GEN-LAST:event_TFamountKeyTyped

    private void TFmedicalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFmedicalKeyTyped
        char c=evt.getKeyChar();
        if( ! (Character.isDigit(c))){
          getToolkit().beep();
          evt.consume();
      }
    }//GEN-LAST:event_TFmedicalKeyTyped

    private void TFbonusKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFbonusKeyTyped
        char c=evt.getKeyChar();
        if( ! (Character.isDigit(c))){
          getToolkit().beep();
          evt.consume();
      }
    }//GEN-LAST:event_TFbonusKeyTyped

    private void TFotherKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFotherKeyTyped
        char c=evt.getKeyChar();
        if( ! (Character.isDigit(c))){
          getToolkit().beep();
          evt.consume();
      }
    }//GEN-LAST:event_TFotherKeyTyped

    private void CBtypeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CBtypeItemStateChanged
       if(CBtype.getSelectedIndex()==1 || CBtype.getSelectedIndex()==2){
           TFhour.setText("");
       }
       if(CBtype.getSelectedIndex()==0){
           TFhour.setText("0");
       }
    }//GEN-LAST:event_CBtypeItemStateChanged
     
    public void advanceSearch(String query){
         try(Connection con = DriverManager.getConnection(url, user, password)){
          
                         
               pst=con.prepareStatement(query);
               pst.setString(1, TFsearch.getText());
               rs=pst.executeQuery();
               if(rs.next()){
                   String serialNo=rs.getString("serialNo");
                   TFserialNo.setText(serialNo);
               
                   
                  String name = rs.getString("name");
                   TFname.setText(name);
                   
                   String address = rs.getString("address");
                   TFaddress.setText(address);
                   
                   String contactNo = rs.getString("contactNo");
                   TFsalary.setText(contactNo);
                   
                   //RADIO BUTTON
                   
                   String gender = rs.getString("gender");
                   if(gender=="Male"){
                       RBmale.setSelected(true);
                       RBfemale.setSelected(false);
                   }
                   else{
                       RBfemale.setSelected(true);
                       RBmale.setSelected(false);
                   }
                   
                   //COMBO BOX
                   String workingType=rs.getString("workingType");
                   if((workingType)=="Full Time"){
                       CBworkingType.setSelectedItem(workingType);
                   }
                   else
                   {
                       CBworkingType.setSelectedItem("Part Time");
                   }
                   String date = rs.getString("entryDate");
                   
                   
                   ((JTextField)JentryDate.getDateEditor().getUiComponent()).setText(date);
                   
                   String rank = rs.getString("rank");
                   
                   switch(rank){  
                       case "Cutting":
                           
                           CBtype.setSelectedItem("Cutting");
                           break;
                       case "Sewing":
                           CBtype.setSelectedItem("Sewing");
                           break;
                       case "Maintenance":
                           CBtype.setSelectedItem("Maintenance");
                           break;
                        case "Finishing":
                           CBtype.setSelectedItem("Finishing");
                           break;
                        case "Accounts Officer":
                           CBtype.setSelectedItem("Accounts Officer");
                           break;
                        case "Manager":
                           CBtype.setSelectedItem("Manager");
                           break;
                        case "Other":
                           CBtype.setSelectedItem("Other");
                           break;
                        default:
                            CBtype.setSelectedItem("Cutting");
                           
                           
                   }
                   //int salary=Integer.valueOf(rs.getString("bSalary"));
                   String salary = rs.getString("bSalary");
                   TFhour.setText(salary);
                   byte[] img=rs.getBytes("image");
                   ImageIcon icon = new ImageIcon(new ImageIcon(img).getImage().getScaledInstance(imageLabel.getWidth(), imageLabel.getHeight(), Image.SCALE_SMOOTH));
                   imageLabel.setIcon(icon);
                   
              
              }
              
           
       } catch (SQLException ex) {
            Logger.getLogger(Vendor.class.getName()).log(Level.SEVERE, null, ex);
            
        }
        
    }
    public void refresh(){
       TFserialNo.setText("");
       TFname.setText("");
       CBreason.setSelectedIndex(0);
       CBtype.setSelectedIndex(0);
       TFhour.setText("");

       TFsearch.setText("");
        //imageLabel.setIcon(null);
    }
    public void getComoboxValue(){
        try(Connection con = DriverManager.getConnection(url, user, password)){
            String query= "SELECT serialNo FROM "+TABLE_NAME;
            pst=con.prepareStatement(query);
            rs=pst.executeQuery();
            while(rs.next()){
                
              
              CBselect.addItem(rs.getString("serialNo"));
            }
            int totalItem=CBselect.getItemCount();
            System.out.println(totalItem);
            
            
            
        } catch (SQLException ex) {
            Logger.getLogger(Payroll.class.getName()).log(Level.SEVERE, null, ex);
        }
    }  
    public void showSelectedInfo(){
        
        try(Connection con = DriverManager.getConnection(url, user, password)){
            
            String id=CBselect.getSelectedItem().toString();
            
            String searchQuery="SELECT * FROM employee WHERE serialNo=?";
            
            pst=con.prepareStatement(searchQuery);
          
            pst.setString(1, CBselect.getSelectedItem().toString());
            
           
            rs=pst.executeQuery();
            if(rs.next()){
                  String serialNo=rs.getString("serialNo");
                   TFserialNo.setText(serialNo);
               
                   
                   String name = rs.getString("name");
                   TFname.setText(name);
                   
                   String workType = rs.getString("workingType");
                   TFworkingType.setText(workType);
                   
                   String rank = rs.getString("rank");
                   TFrank.setText(rank);
                   
                   String salary = rs.getString("bSalary");
                   TFsalary.setText(salary);
                   
                   
                          
            }
            
           } catch (SQLException ex) {
            Logger.getLogger(Payroll.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Payroll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Payroll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Payroll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Payroll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Payroll().setVisible(true);
               
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBmonth;
    private javax.swing.JComboBox<String> CBreason;
    private javax.swing.JComboBox<String> CBselect;
    private javax.swing.JComboBox<String> CBtype;
    private javax.swing.JTextField TFamount;
    private javax.swing.JTextField TFbonus;
    private javax.swing.JTextField TFhour;
    private javax.swing.JTextField TFmedical;
    private javax.swing.JTextField TFname;
    private javax.swing.JTextField TFother;
    private javax.swing.JTextField TFrank;
    private javax.swing.JTextField TFsalary;
    private javax.swing.JTextField TFserialNo;
    private javax.swing.JTextField TFtotalSalary;
    private javax.swing.JTextField TFworkingType;
    private javax.swing.JButton btnCalculate;
    private javax.swing.JButton btnSalarySlip;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel dynamicButtonAdd;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel labelHome;
    private javax.swing.JLabel labelViewALL;
    // End of variables declaration//GEN-END:variables
}
