/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author purba
 */
public class UpdateProfile extends javax.swing.JFrame {

     PreparedStatement pst = null;
    ResultSet rs = null;
    String dbName = "gmsDB";
    String user = "root";
    String password = "";
    String url = "jdbc:mysql://localhost/" + dbName;
    public static final String TABLE_NAME="admin";
    public UpdateProfile() {
        initComponents();
        getInfo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        labelHome = new javax.swing.JLabel();
        logout = new javax.swing.JLabel();
        innerPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        TFname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TFcontactNo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        TFusername = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TFaddress = new javax.swing.JTextArea();
        TFpassword = new javax.swing.JPasswordField();
        updateLabel = new javax.swing.JLabel();
        addAdmin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setLocation(new java.awt.Point(250, 20));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(45, 118, 232));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/group_52px_1.png"))); // NOI18N
        jLabel15.setText("Profile");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 77, -1, -1));

        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/icons8_Delete32.png_32.png"))); // NOI18N
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                exitMousePressed(evt);
            }
        });
        jPanel1.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 10, -1, -1));

        jPanel2.setPreferredSize(new java.awt.Dimension(850, 463));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/icons8_Home_Page.png_32.png_32.png"))); // NOI18N
        labelHome.setToolTipText("Home");
        labelHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelHomeMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                labelHomeMousePressed(evt);
            }
        });
        jPanel2.add(labelHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/icons8_Sign_Out_48px.png"))); // NOI18N
        logout.setToolTipText("Log Out");
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });
        jPanel2.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, -1, -1));

        innerPanel.setBackground(new java.awt.Color(153, 153, 255));

        jLabel3.setText("Name");

        TFname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFnameActionPerformed(evt);
            }
        });

        jLabel4.setText("Address");

        jLabel5.setText("Contact No");

        jLabel6.setText("User Name");

        jLabel7.setText("Password");

        TFaddress.setColumns(20);
        TFaddress.setRows(5);
        jScrollPane1.setViewportView(TFaddress);

        TFpassword.setText("jPasswordField1");

        updateLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/icons8_Checked_48px.png"))); // NOI18N
        updateLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout innerPanelLayout = new javax.swing.GroupLayout(innerPanel);
        innerPanel.setLayout(innerPanelLayout);
        innerPanelLayout.setHorizontalGroup(
            innerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(innerPanelLayout.createSequentialGroup()
                .addGroup(innerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(innerPanelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(innerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(51, 51, 51)
                        .addGroup(innerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TFname)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                            .addComponent(TFusername)
                            .addComponent(TFcontactNo)
                            .addComponent(TFpassword)))
                    .addGroup(innerPanelLayout.createSequentialGroup()
                        .addGap(212, 212, 212)
                        .addComponent(updateLabel)))
                .addContainerGap(153, Short.MAX_VALUE))
        );
        innerPanelLayout.setVerticalGroup(
            innerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(innerPanelLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(innerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TFname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(innerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(innerPanelLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel4)
                        .addGap(32, 32, 32))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, innerPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(innerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TFcontactNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(innerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(TFusername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(innerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(TFpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(updateLabel)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        jPanel2.add(innerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 500, 410));

        addAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/icons8_Add_User_Male.png_32.png"))); // NOI18N
        addAdmin.setToolTipText("Add New Admin");
        addAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addAdminMouseClicked(evt);
            }
        });
        jPanel2.add(addAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 50, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMousePressed
        System.exit(0);
    }//GEN-LAST:event_exitMousePressed

    private void labelHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelHomeMouseClicked
       this.dispose();
       new Home().setVisible(true);
    }//GEN-LAST:event_labelHomeMouseClicked

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        this.dispose();
        new Login().show();
    }//GEN-LAST:event_logoutMouseClicked

    private void labelHomeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelHomeMousePressed
       /*is.dispose()
       new Home().setVisible(true);*/
    }//GEN-LAST:event_labelHomeMousePressed

    private void TFnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFnameActionPerformed

    private void addAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addAdminMouseClicked
        this.dispose();
        new AddAdmin().show();
    }//GEN-LAST:event_addAdminMouseClicked

    private void updateLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateLabelMouseClicked
         try(Connection con = DriverManager.getConnection(url, user, password)){
             String username=TFusername.getText();
             String name=TFname.getText();
             String address=TFaddress.getText();
             String password=TFpassword.getText();
             String contactNo=TFcontactNo.getText();
             
             String query = "UPDATE admin SET adminName='"
            +name+"',adminAddress='"+address+"',adminContactNo='"
            +contactNo+"',username='"
            +username+"',password='"+password+"' where adminName='"
            +name+"';";
 
                    pst = con.prepareStatement(query);
                     
 
                 int rowsUpdated = pst.executeUpdate();
                 //pst.execute();
                 if (rowsUpdated > 0) {
                JOptionPane.showMessageDialog(null,"Your Profile is updated susuccessfully!");
                   }
         } catch (SQLException ex) {
             Logger.getLogger(UpdateProfile.class.getName()).log(Level.SEVERE, null, ex);
         }
    }//GEN-LAST:event_updateLabelMouseClicked
    public void refresh(){
      // TFserialNo.setText("");
       
    }
    public void getInfo(){
        try(Connection con = DriverManager.getConnection(url, user, password)){
            String query="SELECT * FROM "+TABLE_NAME+" WHERE username='"+new Login().loggedUserName+"';";
            //String query="SELECT * FROM "+TABLE_NAME+" WHERE username="+new Login().loggedUserName+";";
            pst=con.prepareStatement(query);
            rs=pst.executeQuery();
            if(rs.next()){
                String name = rs.getString("adminName");
                TFname.setText(name);
                
                String address = rs.getString("adminAddress");
                TFaddress.setText(address);
                
                String contactNo = rs.getString("adminContactNo");
                TFcontactNo.setText(contactNo);
                
                String username = rs.getString("username");
                TFusername.setText(username);
               
                String password = rs.getString("password");
                TFpassword.setText(password);
                                   
            }
            
        } catch (SQLException ex) {
             Logger.getLogger(UpdateProfile.class.getName()).log(Level.SEVERE, null, ex);
         }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateProfile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea TFaddress;
    private javax.swing.JTextField TFcontactNo;
    private javax.swing.JTextField TFname;
    private javax.swing.JPasswordField TFpassword;
    private javax.swing.JTextField TFusername;
    private javax.swing.JLabel addAdmin;
    private javax.swing.JLabel exit;
    private javax.swing.JPanel innerPanel;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelHome;
    private javax.swing.JLabel logout;
    private javax.swing.JLabel updateLabel;
    // End of variables declaration//GEN-END:variables
}
